### ISSUE TITLE
Change the value of the selected option from String to Text Widget

### ISSUE THREAD

**Issue by maikksmt** [davigmacode/flutter_smart_select#102]
Hello,

I want to ask for a change in tile.dart for class S2Tile<T> from 
```
    /// The value of the selected option.
    final String value; 
```
to 
```
    final Widget value;
```
and further dependent adaptions
to have the same customization options available as for 
```
    /// The primary content of the list tile.
    final Widget title;
```
<img width="498" alt="Bildschirmfoto 2021-08-09 um 21 19 56" src="https://user-images.githubusercontent.com/29897807/128762119-3708a224-cd8f-4d4b-8bb5-6fd4401fbc0d.png">

for now I have to edit ```_valueWidge{}``` within tile.dart to handle long text to 2 lines when overflow or set font size to get every option into single line.
So I would like to have an option to customize it inside my project.
<img width="314" alt="Bildschirmfoto 2021-08-09 um 21 25 39" src="https://user-images.githubusercontent.com/29897807/128762687-b92c5579-e103-4f15-a18d-da4ac1f36289.png">
<img width="297" alt="Bildschirmfoto 2021-08-09 um 21 25 59" src="https://user-images.githubusercontent.com/29897807/128762713-0db25522-4e4d-490d-b06a-c4dfb0c0fc50.png">

```
Widget get _valueWidget {
    return Text(
      isLoading ? loadingText : value,
      style: const TextStyle(color: Colors.grey, fontSize: 26.0),
      overflow: TextOverflow.fade,
      softWrap: true,
      maxLines: 2,
    );
  }
```

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by davigmacode** [comment]
Hi everyone,

I'm sorry to announce that I'm no longer maintaining the [smart_select](https://pub.dev/packages/smart_select) package. It's been a great project, but it's become too difficult to maintain.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [smart_select](https://pub.dev/packages/smart_select).

Thanks for your understanding.
