### ISSUE TITLE
Can you add null-safety to the lib?

### ISSUE THREAD

**Issue by dnsoumik** [davigmacode/flutter_smart_select#104]

**Comment by explorova** [comment]
+1

**Comment by chrisvidal** [comment]
+1

**Comment by absar** [comment]
Looks like this library is abandoned, however there is a Null safe fork for it https://github.com/akbarpulatov/flutter_awesome_select

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by chrisvidal** [comment]
tested the v6.0.0 null safety and seems to be working well.
thanks

**Comment by vasilich6107** [comment]
@chrisvidal sure thing ;-)

**Comment by davigmacode** [comment]
Hi everyone,

I'm sorry to announce that I'm no longer maintaining the [smart_select](https://pub.dev/packages/smart_select) package. It's been a great project, but it's become too difficult to maintain.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [smart_select](https://pub.dev/packages/smart_select).

Thanks for your understanding.
