### ISSUE TITLE
Add new Item into list

### ISSUE THREAD

**Issue by alexaung** [davigmacode/flutter_smart_select#105]
I am using single modal select. Now client want to add item if there is no specific item in list. If user add the new item and then  auto selected that newly added item. Is there a way to integrate with this control.

**Comment by vasilich6107** [comment]
Hi @alexaung as you can see from the commits this library is not supported

I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
I suggest you to switch to new fork

**Comment by alexaung** [comment]
Thanks

**Comment by davigmacode** [comment]
Hi everyone,

I'm sorry to announce that I'm no longer maintaining the [smart_select](https://pub.dev/packages/smart_select) package. It's been a great project, but it's become too difficult to maintain.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [smart_select](https://pub.dev/packages/smart_select).

Thanks for your understanding.
