### ISSUE TITLE
smart_select: ^4.3.2 package error 

### ISSUE THREAD

**Issue by shubhamdtalekar** [davigmacode/flutter_smart_select#106]
../../src/flutter_windows_3.0.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/smart_select-4.3.2/lib/src/widget.dart:833:20: Error: The getter 'FlatButton' isn't defined for the class 'S2State<T>'.       
 - 'S2State' is from 'package:smart_select/src/widget.dart' ('../../src/flutter_windows_3.0.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/smart_select-4.3.2/lib/src/widget.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'FlatButton'.
            child: FlatButton.icon(
                   ^^^^^^^^^^
../../src/flutter_windows_3.0.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/smart_select-4.3.2/lib/src/widget.dart:851:20: Error: The method 'FlatButton' isn't defined for the class 'S2State<T>'.       
 - 'S2State' is from 'package:smart_select/src/widget.dart' ('../../src/flutter_windows_3.0.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/smart_select-4.3.2/lib/src/widget.dart').
Try correcting the name to the name of an existing method, or defining a method named 'FlatButton'.     
            child: FlatButton(
                   ^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\shubham\src\flutter_windows_3.0.1-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\shubham\src\flutter_windows_3.0.1-stable\flutter\bin\flutter.bat'' finished with 
non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Running Gradle task 'assembleDebug'...                            204.9s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by mityax** [comment]
As far as I can see, #107 should fix this @davigmacode.

It would be great to have a new release with `TextButton` instead of `FlatButton`, so this nice package is usable again.

**Comment by shimiuh** [comment]
Yup I have the same issue please merge this fix

**Comment by sarn0ld** [comment]
> As far as I can see, #107 should fix this @davigmacode.
> 
> It would be great to have a new release with `TextButton` instead of `FlatButton`, so this nice package is usable again.
> 
> In the meantime, the fork can be used directly:
> 
> ```yaml
> smart_select: #^4.3.2  # 4.3.2 still uses the old FlatButton instead of TextButton, this fork has it fixed.
>     git:
>       ref: "abdulreman/moduleUpgrade"
>       url: "https://github.com/arsarsars1/flutter_smart_select.git"
> ```

That fork was deleted. 
We now switched to the fork https://pub.dev/packages/awesome_select - It made some API Changes but it is actively maintained and working nicely again.

**Comment by davigmacode** [comment]
Hi everyone,

I'm sorry to announce that I'm no longer maintaining the [smart_select](https://pub.dev/packages/smart_select) package. It's been a great project, but it's become too difficult to maintain.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [smart_select](https://pub.dev/packages/smart_select).

Thanks for your understanding.
