### ISSUE TITLE
Key:key

### ISSUE THREAD

**Issue by khosravij** [davigmacode/flutter_smart_select#12]
Could you please share the example How to use the set key so that we can use the value elsewhere?

**Comment by davigmacode** [comment]
As usually, but, I don't think it will help much to get widget state in version 3.x.x. ([4.x.x](https://github.com/davigmacode/flutter_smart_select/tree/v4.0.0) not released yet) 
```dart
final key = GlobalKey();

SmartSelect<T>.single/multiple(
  key: key,
)
```
Could you give me a sample case that need to access the value from widget key? I think this example below (without key) is fine enough, you can use the value elsewhere
```dart
String value = 'flutter';

List<S2Option<String>> options = [
  S2Option<String>(value: 'ion', title: 'Ionic'),
  S2Option<String>(value: 'flu', title: 'Flutter'),
  S2Option<String>(value: 'rea', title: 'React Native'),
];

@override
Widget build(BuildContext context) {
  return SmartSelect<String>.single(
    title: 'Frameworks',
    value: value,
    options: options,
    onChange: (val) => setState(() => value = val)
  );
}
```

**Comment by khosravij** [comment]
tnx

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?
