### ISSUE TITLE
Search based screens are not responding on iOS simulator iPhone 11 - 13.3

### ISSUE THREAD

**Issue by JigneshPatel23** [davigmacode/flutter_smart_select#14]
Search based screens are not responding on iOS simulator iPhone 11 - 13.3

![Simulator Screen Shot - iPhone 11 - 2020-05-21 at 14 51 40](https://user-images.githubusercontent.com/7347854/82544947-86015500-9b73-11ea-9183-c5594c5d5c39.png)

![Simulator Screen Shot - iPhone 11 - 2020-05-21 at 14 50 15](https://user-images.githubusercontent.com/7347854/82544952-88fc4580-9b73-11ea-8035-52b151024257.png)

`flutter doctor -v`

[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-IN)
    • Flutter version 1.17.0 at /Users/abc/development/flutter
    • Framework revision e6b34c2b5c (3 weeks ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/abc/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/abc/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • iPhone 11  • 30D5A8D5-FA1D-4E56-9D57-204A4B52E404 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Chrome     • chrome                               • web-javascript • Google Chrome 81.0.4044.138
    • Web Server • web-server                           • web-javascript • Flutter Tools

**Comment by davigmacode** [comment]
Hi @JigneshPatel23, I apologize for this long response.
Please upgrade to the latest 4.x.x. version and test it again.
Because I don't have any Mac or iPhone device

Please reopen this issue if it still fails.
Thanks

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?
