### ISSUE TITLE
can "SmartSelect<String>.multiple"  have single select in same group ? 

### ISSUE THREAD

**Issue by sunshineinwater** [davigmacode/flutter_smart_select#16]
Here is the situation:
     I want select multi  tags in many groups of tag ,  but in one group I need to select a single tag.  
     Have it  this function ?

**Comment by davigmacode** [comment]
Hi @sunshineinwater, I apologize for this long response.
Please upgrade to the latest 4.x.x. version and check the [validation example](https://github.com/davigmacode/flutter_smart_select/blob/master/example/lib/features_modal/modal_validation.dart) or [selector example](https://github.com/davigmacode/flutter_smart_select/blob/master/example/lib/features_modal/modal_selector.dart)

[![Modal Validation](https://raw.githubusercontent.com/davigmacode/flutter_smart_select/master/demo/screens/modal-validation.gif)](https://github.com/davigmacode/flutter_smart_select/blob/master/example/lib/features_modal/modal_validation.dart) [![Modal Selector](https://raw.githubusercontent.com/davigmacode/flutter_smart_select/master/demo/screens/modal-selector.gif)](https://github.com/davigmacode/flutter_smart_select/blob/master/example/lib/features_modal/modal_selector.dart)

Thanks

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?
