### ISSUE TITLE
change direction ( to rtl ) in SmartSelectModal ?

### ISSUE THREAD

**Issue by ebrahimimasod** [davigmacode/flutter_smart_select#17]
Hi 
Thank you for this usefull package .
how i can change direction  in SmartSelectModal  ?

**Comment by davigmacode** [comment]
Hi @ebrahimimasod, I apologize for this long response.
Please upgrade to the latest 4.x.x version

Currently there is no special parameter to change direction to RTL, but you can build your custom modal header widget using `modalHeaderBuilder` or `builder.modalHeader`. All available widget builder can be found [here](https://github.com/davigmacode/flutter_smart_select#builder-widget)

Thanks

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?
