### ISSUE TITLE
how to change font size for title

### ISSUE THREAD

**Issue by serahzaveri** [davigmacode/flutter_smart_select#19]
I'm having trouble changing the font size of the title. I tried changing the font size of the modal header but that does not change the font size of the title. 
Any help will be really appreciated. Thanks.

Padding(
          padding: const EdgeInsets.only(top: 35.0),
          child: SmartSelect<String>.single(
                   title: "House Type", //i want to change the font size of this on the form
                   value: this._houseType,
                   options: options.houseType,
                   onChange: (val) => setState(() => this._houseType = val),
                   modalType: SmartSelectModalType.bottomSheet,
                   modalConfig: SmartSelectModalConfig(
                          headerStyle: SmartSelectModalHeaderStyle(
                                textStyle: TextStyle(
                                  fontSize: 28.0
                                )
                              )
                            )
                          ),
                        ),

**Comment by Katekko** [comment]
I wanna change the color, but I don't know how...

**Comment by heypran** [comment]
> @serahzaveri @Katekko
> I am facing the same issue... but I found a way, Change the title style for `class SmartSelectTile extends StatelessWidget ` in the package code.
> 
> But then packages are stored in cache and this will be removed if other people will setup the project. as package will be installed from flutter pub repository.
> 
> A good solution is to expose it and make it configurable similar to `SmartSelectModalConfig` but I dont know how to do that.
> 
> @davigmacode i believe you can guide me on this, I will create a PR.

I made the changes need sometime to test and  create a PR

**Comment by davigmacode** [comment]
> I'm having trouble changing the font size of the title. I tried changing the font size of the modal header but that does not change the font size of the title.
> Any help will be really appreciated. Thanks.
> 
> Padding(
> padding: const EdgeInsets.only(top: 35.0),
> child: SmartSelect.single(
> title: "House Type", //i want to change the font size of this on the form
> value: this._houseType,
> options: options.houseType,
> onChange: (val) => setState(() => this._houseType = val),
> modalType: SmartSelectModalType.bottomSheet,
> modalConfig: SmartSelectModalConfig(
> headerStyle: SmartSelectModalHeaderStyle(
> textStyle: TextStyle(
> fontSize: 28.0
> )
> )
> )
> ),
> ),

Hi @serahzaveri,  I apologize for this long response.
Please upgrade to the latest 4.x.x.

Change the configuration to
```dart
Padding(
  padding: const EdgeInsets.only(top: 35.0),
  child: SmartSelect.single(
    title: "House Type",
    value: this._houseType,
    onChange: (state) => setState(() => this._houseType = state.value),
    choiceItems: options.houseType,
    modalType: S2ModalType.bottomSheet,
    modalHeaderStyle: S2ModalHeaderStyle(
      textStyle: TextStyle(
        fontSize: 28.0
      ),
    ),
  ),
),
```

Please reopen this issue if it still fails.

Thanks

**Comment by davigmacode** [comment]
> I wanna change the color, but I don't know how...

Hi @Katekko, what color? can be more specific?

**Comment by davigmacode** [comment]
> @serahzaveri @Katekko
> I am facing the same issue... but I found a way, Change the title style for `class SmartSelectTile extends StatelessWidget ` in the package code.
> 
> But then packages are stored in cache and this will be removed if other people will setup the project. as package will be installed from flutter pub repository.
> 
> A good solution is to expose it and make it configurable similar to `SmartSelectModalConfig` but I dont know how to do that.
> 
> @davigmacode i believe you can guide me on this, I will create a PR.

Hi @heypran, I have responded to the [pull request](https://github.com/davigmacode/flutter_smart_select/pull/20)

Thanks

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?
