### ISSUE TITLE
Can't edit margin/height or style?

### ISSUE THREAD

**Issue by cn-Meepo** [davigmacode/flutter_smart_select#2]
Excuse me, Could I edit the magin , height or style by myself?

**Comment by davigmacode** [comment]
Actually you can customize almost everything, please look at the [example](https://pub.dev/packages/smart_select#-example-tab-) or [API Reference](https://pub.dev/documentation/smart_select/latest/smart_select/smart_select-library.html) for full documentation

**Comment by cn-Meepo** [comment]
@davigmacode thanks

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?
