### ISSUE TITLE
[Question] How to implement a select all functionality in multi-select mode?

### ISSUE THREAD

**Issue by Hasilt** [davigmacode/flutter_smart_select#21]
Hello,
Is there any option to select all options in multi-select mode? I couldn't find it in the docs. 

I can help if it's not there.

Thanks

**Comment by davigmacode** [comment]
Hi @Hasilt, I apologize for this long response.
Please upgrade to the latest 4.x.x version and check these [example](https://github.com/davigmacode/flutter_smart_select/blob/master/example/lib/features_modal/modal_selector.dart)

[![Modal Selector](https://raw.githubusercontent.com/davigmacode/flutter_smart_select/master/demo/screens/modal-selector.gif)](https://github.com/davigmacode/flutter_smart_select/blob/master/example/lib/features_modal/modal_selector.dart)

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?
