### ISSUE TITLE
This application cannot tree shake icons fonts when build

### ISSUE THREAD

**Issue by harrykc** [davigmacode/flutter_smart_select#24]
Hi, thanks for your great package, I just upgrade to the latest version(4.2.0), an exception when build the appbundle, it says.

```
This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations:
  - file:///Users/xxxxx/development/tools/flutter/.pub-cache/hosted/pub.dartlang.org/smart_select-4.2.0/lib/src/choices_empty.dart:17:15
```

I using --no-tree-shake-icons flag to avoid this error at the moment, hope will fix in next version, thanks.

**Comment by riamehdi** [comment]
We will wait for a fix.
You can build with :
`flutter build apk --release --no-tree-shake-icons`

**Comment by mauriziopinotti** [comment]
Just added a pull request for this issue: https://github.com/davigmacode/flutter_smart_select/pull/28

**Comment by davigmacode** [comment]
I just updated the package, please upgrade to 4.2.1

> Just added a pull request for this issue: #28

I'm sorry, I didn't see your reply, thanks for contributing

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?
