### ISSUE TITLE
Add subtitle

### ISSUE THREAD

**Issue by vivinapriyanti** [davigmacode/flutter_smart_select#3]
Excuse me, i want to make subtitle and sub subtitle. but in your library only provide subtitle. and i try to make a column in subtitle like this. but i got error "The expression doesn't evaluate to a function, so it can't be invoked."

`              subtitle: (index, item) => widget(
                    child: Column(children: <Widget>[
                      Text(NumberFormat.currency(
                              locale: "id", symbol: 'Rp ', decimalDigits: 0)
                          .format(int.parse(item['harga'].split(".")[0]))),
                      Text(item['working_duration'])
                    ]),
                  )`

**Comment by davigmacode** [comment]
the `subtitle` parameter from [`SmartSelectOption<T>.listFrom<R, E>`](https://pub.dev/documentation/smart_select/latest/smart_select/SmartSelectOption/listFrom.html) function should return `String` not widget, you can use [`choiceConfig.builder`](https://pub.dev/documentation/smart_select/latest/smart_select/SmartSelectChoiceConfig/builder.html) parameter to build your own choice widget
```
SmartSelect<T>.single/multiple(
  choiceConfig: SmartSelectChoiceConfig(
    builder: (option, selected, onSelect) {
      return ListTile(
        title: Text(option.title),
        subtitle: Text(option.subtitle),
        onTap: () => onSelect(option.value, true),
        leading: CircleAvatar(
          backgroundImage: NetworkImage(option.meta['image']),
          child: selected ? Icon(
            Icons.check,
            color: Colors.white,
          ) : null,
        ),
      );
    }
  ),
);
```

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?
