### ISSUE TITLE
Can we customize widget that open choices?

### ISSUE THREAD

**Issue by Slava96** [davigmacode/flutter_smart_select#30]
I try to find a builder that can customize widget that opens a selection box with choices, but cannot find it.
Do you have this one?

**Comment by davigmacode** [comment]
Sure, you can use `tileBuilder`

```dart
// default trigger widget usage example
SmartSelect<T>.single(
  ...,
  ...,
  tileBuilder: (context, state) {
    return S2Tile(
      title: state.titleWidget,
      value: state.valueDisplay,
      onTap: state.showModal,
      isLoading: true,
    );
  },
);

// default trigger widget from state
SmartSelect<T>.multiple(
  ...,
  ...,
  tileBuilder: (context, state) {
    return S2Tile.fromState(
      state,
      value: 'override the value',
      isLoading: true,
    );
  },
);

// or use your own widget
SmartSelect<T>.single(
  ...,
  ...,
  tileBuilder: (context, state) {
    return MyTriggerWidget();
  },
);
```

**Comment by masseelch** [comment]
We can indeed do that. But still the `title` remains. It is not possible to get rid of it completely. I'd like to use `SmartSelect` in a bigger form and want to use floating labels only. I can not do that right now, can I?

**Comment by masseelch** [comment]
NVM! I was just too stupid :cry:

**Comment by Slava96** [comment]
Yes, this worked!

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?
