### ISSUE TITLE
chipOnDelete don't update

### ISSUE THREAD

**Issue by cosmosdesigner** [davigmacode/flutter_smart_select#45]
Hi all, when i try to delete the chip, the array _prestations is updated and remove the selected item, but the item kept visible, soo, it means that he dont re-render...

`... child: S2Tile.fromState(
                            state,
                            hideValue: true,
                            title: const Text('Cars'),
                            trailing: const Icon(Icons.add_circle_outline),
                            body: S2TileChips(
                              chipLength: state.valueObject.length,
                              chipLabelBuilder: (context, i) {
                                return Text(state.valueObject[i].title);
                              },
                              chipOnDelete: (i) => setState(() {
                                _prestations.remove(state.valueObject[i].value);
                              }),
                              chipColor: IntervenantThemeColors.primaryColor,
                            ),
                          )`

Thank you.

**Comment by cosmosdesigner** [comment]
Just figure it out, sorry. My bad.

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?
