### ISSUE TITLE
Change Title Text Color?

### ISSUE THREAD

**Issue by halahmadi** [davigmacode/flutter_smart_select#5]
One of the required inputs to SmartSelect is "title", and the default display color for the title is black. How can I modify the color?

**Comment by davigmacode** [comment]
If you mean is customizing modal header text color you can refer to this [example](https://github.com/davigmacode/flutter_smart_select/blob/master/example/lib/features_choices/choices_theme.dart#L44)

**Comment by ench0** [comment]
Wow, this really has it all. Job well done!

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?
