### ISSUE TITLE
Filter: how to change "No matches" text?

### ISSUE THREAD

**Issue by lore-co** [davigmacode/flutter_smart_select#68]
Is it possible to add the possibility of changing the "no matches" text that the filter automatically display? It would be great for localization needs. Thanks!

**Comment by minchemo** [comment]
There is a **choiceEmptyBuilder** , it is simply to use it.

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?
