### ISSUE TITLE
How to trigger the modal search bar without clicking on the search icon

### ISSUE THREAD

**Issue by Mr-Bajalan** [davigmacode/flutter_smart_select#69]
I not really sure if this feature is supported or not, if not, I think it would be great to have it.

**Comment by Mr-Bajalan** [comment]
I used the modalHeaderBuilder and it worked like a magic.

**Comment by killerhp12** [comment]
> I used the modalHeaderBuilder and it worked like a magic.

can you show me an example, thanks

**Comment by fabiodrs** [comment]
Didn't make it work. Any help?

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?
