### ISSUE TITLE
Network fetched options

### ISSUE THREAD

**Issue by itsgauravjain22** [davigmacode/flutter_smart_select#8]
Could you please share the example of displaying options after fetched from network API. Could I display loading indicator till the response is fetched?

**Comment by davigmacode** [comment]
Yes you can display loading indicator, here the [example](https://github.com/davigmacode/flutter_smart_select/blob/master/example/lib/features_option/option_async.dart). 
Also you can find another example in [this page](https://github.com/davigmacode/flutter_smart_select/tree/master/example)

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?
