### ISSUE TITLE
Error in null saftey for change

### ISSUE THREAD

**Issue by bibekmakaju** [davigmacode/flutter_smart_select#86]
onChange : (selected){

}
while changing
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type '(S2SingleSelected<String>) => void' is not a subtype of type '((S2SingleSelected<String?>) => void)?'

E/flutter (10308): #0      S2SingleState.onChange
package:smart_select/src/widget.dart:1709

E/flutter (10308): #1      S2State.showModal
package:smart_select/src/widget.dart:1630

**Comment by simonkimi** [comment]
> 
> 
> onChange : (selected){
> 
> }
> while changing
> [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type '(S2SingleSelected) => void' is not a subtype of type '((S2SingleSelected<String?>) => void)?'
> 
> E/flutter (10308): #0 S2SingleState.onChange
> package:smart_select/src/widget.dart:1709
> 
> E/flutter (10308): #1 S2State.showModal
> package:smart_select/src/widget.dart:1630

```dart
import 'package:smart_select/src/model/chosen.dart';
.....
onChange: (S2SingleSelected<String?> value) {
    ....
}
```

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by kapil708** [comment]
> I released https://pub.dev/packages/flutter_awesome_select with fixed null safety. Could you check that everything works for you?

Work for me :)
