### ISSUE TITLE
nested smart_select (how to open a new smart select modal after making a choice in the first one)

### ISSUE THREAD

**Issue by amoo12** [davigmacode/flutter_smart_select#88]
Hi, I am trying to make 2 smart_select where making a choice in the first one opens the second, this is needed in some cases. Here is an example of the desired outcome.

https://user-images.githubusercontent.com/49261542/115127439-16a51700-a009-11eb-947f-ded2c75d1b38.mp4

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?
