### ISSUE TITLE
Accents and filter

### ISSUE THREAD

**Issue by pblinux** [davigmacode/flutter_smart_select#9]
Hi I want to start by saying, smart_select is awesome, thanks for this helpful package!

When it's filtering and the query or result item have and accent mark, nothing returns. I don't know if this is an expected behaviour but I think I fixed it in https://github.com/pblinux/flutter_smart_select/tree/accents.
Can I make pull request of this?

Also, I needed to filtering be auto. https://github.com/pblinux/flutter_smart_select/tree/autofilter
Would this be something useful?

Thanks.

**Comment by davigmacode** [comment]
Great, glad it was so well received. 

I really appreciate you taking the time to improve this package, currently i'm working on huge update with breaking changes, i have just finish the functionality but need few days or week to finalize few things like example, documentation, and other minor features. Please see the new code in [this branch](https://github.com/davigmacode/flutter_smart_select/tree/v4.0.0), you are welcoming to create a pull request to that branch, and will be available in the next release.

I have reviewed your code, 
For accent mark, are there alternatives to using an external package?
For filter autocomplete, its useful, only need to add debouncer, i'll do it later

Thanks

**Comment by pblinux** [comment]
Hi @davigmacode.

Great! I will create the pull requests to that branch, thanks. For accent marks, I think it can be made without a external package, I will work on that.

**Comment by davigmacode** [comment]
Thanks, i have merge the pull requests, i will close this issue then.

**Comment by Freyien** [comment]
Hi, this is a great package.

Im waiting for the updates :D :D :dagger:

Thanks for the time and for share

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?
