### ISSUE TITLE
Radio, checkbox and chips in the same modal

### ISSUE THREAD

**Issue by RicardoRB** [davigmacode/flutter_smart_select#93]
Hi all!

Is it possible to have multi selects? (radio, chips and checkbox) Same as Uber Eats.

Example:

![photo_2021-05-16_19-49-43](https://user-images.githubusercontent.com/3050311/118407204-e4c2b700-b67f-11eb-9647-aa33820a806f.jpg)

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by davigmacode** [comment]
Hi everyone,

I'm sorry to announce that I'm no longer maintaining the [smart_select](https://pub.dev/packages/smart_select) package. It's been a great project, but it's become too difficult to maintain.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [smart_select](https://pub.dev/packages/smart_select).

Thanks for your understanding.
