### ISSUE TITLE
Is the package still maintained?

### ISSUE THREAD

**Issue by herman-the-worm** [davigmacode/flutter_smart_select#94]
I see so many open issues and none of them addressed including null safety.

Is it safe to assume that this library won't be receiving updates from the maintainers anymore?

Thanks

**Comment by ayberkcal** [comment]
I have sent a mail to repo owner but he did not response. I hope he is fine. Package is very powerful and popular. I think we should discuss fork the repo.

**Comment by divan** [comment]
Any news on the fork?

Package is great, and needs a bit of love.

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by davigmacode** [comment]
Hi everyone,

I'm sorry to announce that I'm no longer maintaining the [smart_select](https://pub.dev/packages/smart_select) package. It's been a great project, but it's become too difficult to maintain.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [smart_select](https://pub.dev/packages/smart_select).

Thanks for your understanding.
