### ISSUE TITLE
Color problem in dark theme

### ISSUE THREAD

**Issue by A1Gard** [davigmacode/flutter_smart_select#96]
Report bug:

We have problem when out application is dark mode:

![image](https://user-images.githubusercontent.com/9222481/127438634-a1ced841-ed2c-4678-873c-1f57ed08a3d7.png)

**Comment by A1Gard** [comment]
If we change modal background this problem is still exists:

```
modalStyle: S2ModalStyle(
    backgroundColor: Colors.white
  ),
```
![image](https://user-images.githubusercontent.com/9222481/127438921-e632502a-e065-4f73-a8e5-c13b4f274769.png)

**Comment by A1Gard** [comment]
Any reaction?

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by A1Gard** [comment]
Ok i'll try and tell you the result

Thanks

**Comment by davigmacode** [comment]
Hi everyone,

I'm sorry to announce that I'm no longer maintaining the [smart_select](https://pub.dev/packages/smart_select) package. It's been a great project, but it's become too difficult to maintain.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [smart_select](https://pub.dev/packages/smart_select).

Thanks for your understanding.
